import type {
  ATSResult,
  CareerIQResult,
  RecruiterResult,
  RoleMatchResult,
} from "@/intelligence/types/results";

type Props = {
  careerIQ: CareerIQResult;
  ats: ATSResult;
  recruiter: RecruiterResult;
  bestMatch?: RoleMatchResult;
  topImprovement: string;
};

export default function ShareableCareerCard({
  careerIQ,
  ats,
  recruiter,
  bestMatch,
  topImprovement,
}: Props) {
  return (
    <section className="rounded-lg border border-neutral-700 bg-neutral-900 p-6 text-white">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.22em] text-emerald-300">
            SkillMint Career Report
          </p>

          <h2 className="mt-3 text-2xl font-black">
            Shareable Snapshot
          </h2>
        </div>

        <p className="rounded-full border border-neutral-700 px-3 py-1 text-xs font-semibold text-neutral-300">
          Generated by SkillMint
        </p>
      </div>

      <div className="mt-8 grid gap-5">
        <SnapshotRow
          label="Career IQ"
          value={`${Math.round(careerIQ.score)} (${careerIQ.grade})`}
        />

        <SnapshotRow
          label="Best Role"
          value={bestMatch?.role ?? "Not enough data"}
        />

        <SnapshotRow
          label="ATS"
          value={`${Math.round(ats.score)}%`}
        />

        <SnapshotRow
          label="Recruiter Confidence"
          value={`${Math.round(recruiter.score)}%`}
        />

        <SnapshotRow
          label="Top Improvement"
          value={topImprovement}
        />
      </div>
    </section>
  );
}

type SnapshotRowProps = {
  label: string;
  value: string;
};

function SnapshotRow({ label, value }: SnapshotRowProps) {
  return (
    <div className="grid gap-2 border-b border-neutral-800 pb-4 last:border-b-0 last:pb-0 sm:grid-cols-[150px_1fr]">
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-neutral-500">
        {label}
      </p>

      <p className="min-w-0 break-words text-sm font-bold text-white">
        {value}
      </p>
    </div>
  );
}
