"use client";

import Link from "next/link";
import { useState } from "react";

import type {
  ATSResult,
  CareerIQResult,
  RecruiterResult,
  RoleMatchResult,
} from "@/intelligence/types/results";

type Props = {
  careerIQ: CareerIQResult;
  ats: ATSResult;
  recruiter: RecruiterResult;
  bestMatch?: RoleMatchResult;
  isReady: boolean;
  nextProofMove: string;
};

export default function ShareableCareerCard({
  careerIQ,
  ats,
  recruiter,
  bestMatch,
  isReady,
  nextProofMove,
}: Props) {
  const [shareMessage, setShareMessage] = useState("");
  const safeProofMove = getSafeProofMove(nextProofMove);
  const summary = buildShareSummary({
    careerIQ,
    ats,
    recruiter,
    bestMatch,
    nextProofMove: safeProofMove,
  });

  async function handleShare() {
    setShareMessage("");

    try {
      if (navigator.share) {
        await navigator.share({
          title: "SkillMint Career Snapshot",
          text: summary,
        });
        setShareMessage("Summary shared.");
        return;
      }

      await navigator.clipboard.writeText(summary);
      setShareMessage("Summary copied.");
    } catch {
      setShareMessage("Could not share from this browser right now.");
    }
  }

  if (!isReady) {
    return (
      <section className="rounded-3xl border border-white/10 bg-[linear-gradient(145deg,rgba(255,255,255,0.055),rgba(255,255,255,0.025))] p-6 text-white shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.22em] text-emerald-300">
              SkillMint Career Report
            </p>

            <h2 className="mt-3 text-2xl font-black">
              Shareable Snapshot
            </h2>

            <p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-400">
              Upload a resume to generate your shareable career snapshot.
            </p>
          </div>

          <span className="w-fit rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs font-semibold text-neutral-400">
            Locked
          </span>
        </div>

        <Link
          href="/upload"
          className="mt-6 inline-flex rounded-xl bg-emerald-400 px-5 py-3 text-sm font-bold text-slate-950 shadow-lg shadow-emerald-950/30 transition hover:bg-emerald-300"
        >
          Upload resume
        </Link>
      </section>
    );
  }

  return (
    <section className="rounded-3xl border border-white/10 bg-[linear-gradient(145deg,rgba(255,255,255,0.055),rgba(255,255,255,0.025))] p-6 text-white shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.22em] text-emerald-300">
            SkillMint Career Report
          </p>

          <h2 className="mt-3 text-2xl font-black">
            Shareable Snapshot
          </h2>
        </div>

        <div className="flex flex-wrap gap-2 sm:justify-end">
          <p className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs font-semibold text-neutral-300">
            Generated by SkillMint
          </p>

          <button
            type="button"
            onClick={handleShare}
            className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-100 transition hover:border-emerald-300 hover:bg-emerald-400/15"
          >
            Share summary
          </button>
        </div>
      </div>

      <div className="mt-8 grid gap-5">
        <SnapshotRow
          label="Career IQ"
          value={`${Math.round(careerIQ.score)} (${careerIQ.grade})`}
        />

        <SnapshotRow
          label="Best Role"
          value={bestMatch?.role ?? "Not enough data"}
        />

        <SnapshotRow
          label="ATS"
          value={`${Math.round(ats.score)}%`}
        />

        <SnapshotRow
          label="Recruiter Confidence"
          value={`${Math.round(recruiter.score)}%`}
        />

        <SnapshotRow
          label="Next Proof Move"
          value={safeProofMove}
        />
      </div>

      {shareMessage && (
        <p className="mt-5 rounded-2xl border border-white/10 bg-black/25 p-3 text-sm text-neutral-300">
          {shareMessage}
        </p>
      )}
    </section>
  );
}

function buildShareSummary({
  careerIQ,
  ats,
  recruiter,
  bestMatch,
  nextProofMove,
}: Pick<
  Props,
  "careerIQ" | "ats" | "recruiter" | "bestMatch" | "nextProofMove"
>): string {
  return [
    "SkillMint Career Snapshot",
    `Career IQ: ${Math.round(careerIQ.score)} (${careerIQ.grade})`,
    `Best role: ${bestMatch?.role ?? "Not enough data"}`,
    `ATS readiness: ${Math.round(ats.score)}%`,
    `Recruiter confidence: ${Math.round(recruiter.score)}%`,
    `Next proof move: ${nextProofMove}`,
  ].join("\n");
}

function getSafeProofMove(value: string): string {
  const trimmedValue = value.trim();

  if (!trimmedValue || isOperationalTask(trimmedValue)) {
    return "Strengthen one deployed project";
  }

  return trimmedValue;
}

function isOperationalTask(value: string): boolean {
  const normalizedValue = value.toLowerCase();

  return [
    "upload",
    "sign in",
    "signup",
    "create account",
    "setup",
    "choose direction",
    "open dashboard",
    "paste a job description",
  ].some((phrase) => normalizedValue.includes(phrase));
}

type SnapshotRowProps = {
  label: string;
  value: string;
};

function SnapshotRow({ label, value }: SnapshotRowProps) {
  return (
    <div className="grid gap-2 border-b border-white/10 pb-4 last:border-b-0 last:pb-0 sm:grid-cols-[150px_1fr]">
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-neutral-500">
        {label}
      </p>

      <p className="min-w-0 break-words text-sm font-bold text-white">
        {value}
      </p>
    </div>
  );
}
