"use client";

import Link from "next/link";
import { useState } from "react";

import {
  premiumBadge,
  premiumPrimaryCta,
  premiumSurface,
} from "@/components/ui/premium";
import type { ProofScoreResult } from "@/intelligence/proof";
import type {
  ATSResult,
  CareerIQResult,
  RecruiterResult,
  RoleMatchResult,
} from "@/intelligence/types/results";

type Props = {
  careerIQ: CareerIQResult;
  ats: ATSResult;
  recruiter: RecruiterResult;
  bestMatch?: RoleMatchResult;
  isReady: boolean;
  nextProofMove: string;
  proof?: ProofScoreResult;
  latestJobMatch?: {
    title: string;
    matchScore: number;
  } | null;
};

export default function ShareableCareerCard({
  careerIQ,
  ats,
  recruiter,
  bestMatch,
  isReady,
  nextProofMove,
  proof,
  latestJobMatch,
}: Props) {
  const [shareMessage, setShareMessage] = useState("");
  const safeProofMove = getSafeProofMove(nextProofMove);
  const summary = buildShareSummary({
    careerIQ,
    ats,
    recruiter,
    bestMatch,
    latestJobMatch,
    proof,
    nextProofMove: safeProofMove,
  });

  async function handleShare() {
    setShareMessage("");

    try {
      if (navigator.share) {
        await navigator.share({
          title: "SkillMint Career Snapshot",
          text: summary,
        });
        setShareMessage("Summary shared.");
        return;
      }

      await navigator.clipboard.writeText(summary);
      setShareMessage("Summary copied.");
    } catch {
      setShareMessage("Could not share from this browser right now.");
    }
  }

  if (!isReady) {
    return (
      <section className={premiumSurface}>
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">
              SkillMint Career Report
            </p>

            <h2 className="mt-3 text-2xl font-black text-slate-950">
              Shareable Snapshot
            </h2>

            <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">
              Upload a resume to generate your shareable career snapshot.
            </p>
          </div>

          <span className={`${premiumBadge} w-fit`}>
            Locked
          </span>
        </div>

        <Link
          href="/upload"
          className={`${premiumPrimaryCta} mt-6`}
        >
          Upload resume
        </Link>
      </section>
    );
  }

  return (
    <section className={premiumSurface}>
      <div className="overflow-hidden rounded-[1.7rem] border border-slate-200 bg-white shadow-[0_22px_70px_rgba(15,23,42,0.09)]">
        <div className="border-b border-slate-200 bg-slate-950 p-5 text-white sm:p-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-300">
                SkillMint Career Report
              </p>

              <h2 className="mt-3 text-2xl font-black">
                Shareable Snapshot
              </h2>
            </div>

            <div className="flex flex-wrap gap-2 sm:justify-end">
              <p className="rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold text-slate-100">
                Generated by SkillMint
              </p>

              <button
                type="button"
                onClick={handleShare}
                className="inline-flex items-center gap-2 rounded-full border border-emerald-300/40 bg-emerald-300/10 px-3 py-1 text-xs font-semibold text-emerald-100 transition hover:border-emerald-200 hover:bg-emerald-300/15"
              >
                <ShareIcon />
                Share summary
              </button>
            </div>
          </div>
        </div>

        <div className="grid gap-0 lg:grid-cols-[0.9fr_1.1fr]">
          <div className="border-b border-slate-200 bg-emerald-50 p-6 lg:border-b-0 lg:border-r">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-800">
              Career IQ
            </p>

            <div className="mt-3 flex items-end gap-3">
              <p className="text-7xl font-black leading-none tabular-nums text-slate-950">
                {Math.round(careerIQ.score)}
              </p>

              <p className="pb-2 text-2xl font-black text-emerald-800">
                {careerIQ.grade}
              </p>
            </div>

            <p className="mt-4 text-sm leading-6 text-slate-700">
              Trust-adjusted readiness, not a job guarantee.
            </p>
          </div>

          <div className="grid gap-px bg-slate-200 sm:grid-cols-2">
            <SnapshotTile
              label="Profile-fit role"
              value={bestMatch?.role ?? "Not enough data"}
            />

            {proof && (
              <SnapshotTile
                label="Proof Confidence"
                value={`${Math.round(proof.proofConfidenceScore)}% · ${
                  proof.proofCoverageLabel
                }`}
              />
            )}

            <SnapshotTile
              label="ATS / Recruiter"
              value={`${Math.round(ats.score)}% ATS · ${Math.round(
                recruiter.score,
              )}% recruiter`}
            />

            <SnapshotTile
              label="Latest JD Match"
              value={
                latestJobMatch
                  ? `${Math.round(latestJobMatch.matchScore)}% · ${
                      latestJobMatch.title
                    }`
                  : "No JD matched yet"
              }
            />
          </div>
        </div>

        <div className="border-t border-slate-200 bg-white p-5">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">
            Next Proof Move
          </p>

          <p className="mt-2 break-words text-base font-bold leading-7 text-slate-950">
            {safeProofMove}
          </p>
        </div>
      </div>

      {shareMessage && (
        <p className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">
          {shareMessage}
        </p>
      )}
    </section>
  );
}

function buildShareSummary({
  careerIQ,
  ats,
  recruiter,
  bestMatch,
  latestJobMatch,
  proof,
  nextProofMove,
}: Pick<
  Props,
  | "careerIQ"
  | "ats"
  | "recruiter"
  | "bestMatch"
  | "latestJobMatch"
  | "nextProofMove"
  | "proof"
>): string {
  return [
    "SkillMint Career Snapshot",
    `Career IQ: ${Math.round(careerIQ.score)} (${careerIQ.grade})`,
    `Profile-fit role: ${bestMatch?.role ?? "Not enough data"}`,
    `ATS readiness: ${Math.round(ats.score)}%`,
    `Recruiter confidence: ${Math.round(recruiter.score)}%`,
    latestJobMatch
      ? `Latest JD Match: ${Math.round(latestJobMatch.matchScore)}% (${latestJobMatch.title})`
      : null,
    proof
      ? `Proof confidence: ${Math.round(proof.proofConfidenceScore)}% (${proof.proofCoverageLabel})`
      : null,
    `Next proof move: ${nextProofMove}`,
  ].filter(Boolean).join("\n");
}

function getSafeProofMove(value: string): string {
  const trimmedValue = value.trim();

  if (!trimmedValue || isOperationalTask(trimmedValue)) {
    return "Strengthen one deployed project";
  }

  return trimmedValue;
}

function isOperationalTask(value: string): boolean {
  const normalizedValue = value.toLowerCase();

  return [
    "upload",
    "sign in",
    "signup",
    "create account",
    "setup",
    "choose direction",
    "open dashboard",
    "paste a job description",
  ].some((phrase) => normalizedValue.includes(phrase));
}

type SnapshotTileProps = {
  label: string;
  value: string;
};

function SnapshotTile({ label, value }: SnapshotTileProps) {
  return (
    <div className="min-w-0 bg-white p-5">
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
        {label}
      </p>

      <p className="mt-3 min-w-0 break-words text-sm font-bold leading-6 text-slate-950">
        {value}
      </p>
    </div>
  );
}

function ShareIcon() {
  return (
    <svg
      aria-hidden="true"
      className="h-3.5 w-3.5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth="2"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M7 12l10-7v14L7 12z"
      />
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M7 12H4"
      />
    </svg>
  );
}
